FROM  node:22-alpine

WORKDIR /app

COPY client/AlloBoulot/package*.json ./


RUN npm install

COPY client/AlloBoulot .

EXPOSE 5173

# CMD ["npm", "run", "dev"]
CMD ["npm", "run", "dev", "--", "--host"]